library:
  source-dirs: src
  exposed-modules: Acronym
tests:
  test:
    source-dirs: test
    main: Tests.hs
    dependencies:
    - acronym
    - hspec
dependencies:
- split
- base
name: acronym
version: 1.4.0.6
